const CAREER_START = 2019

export function useResumeData() {
  const yearsExp = new Date().getFullYear() - CAREER_START

  const bio = {
    name: 'Mohamed Ibrahim',
    alias: 'YapoeY',
    title: 'Software Engineer',
    location: 'Seoul, South Korea',
    from: 'Egypt',
    email: 'yapoey@gmail.com',
    website: 'yapoey.com',
    github: 'github.com/yapoey',
    linkedin: 'linkedin.com/in/yapoey',
    youtube: 'youtube.com/c/yapoey-tech',
    summary: `Software Engineer with ${yearsExp}+ years of experience building web and mobile applications. Based in Seoul, South Korea, originally from Egypt. I lead frontend teams, architect design systems, and deliver full-stack products for clients in healthcare, education, e-commerce, and SaaS. Currently Senior Frontend Developer & Team Lead at Sibel Health International, and Product Manager & Technical Lead at YapoeY Bit.`,
  }

  const experience = [
    {
      title: 'Senior Frontend Developer & Frontend Team Lead',
      company: 'Sibel Health International',
      type: 'Full-time',
      location: 'Seoul, Korea & US',
      duration: '2022/10 — Present',
      highlights: [
        'Lead frontend team across Korea and US offices',
        'Built Discovery Hub — migrated entire codebase from React to Vue.js from scratch (256 commits)',
        'Built Itchy Sense product for Japanese company Maruho within Discovery platform',
        'Created Sibel Health Design System using atomic design methodology, extracted as shared npm workspace package',
        'Built Central Monitoring (Tucana) — real-time monitoring of 64 patients via WebSocket',
        'Optimized frontend performance for real-time data streaming',
        'Traveled to US (2024) to fix critical issues in Maternal project — helped company achieve FDA approval',
        'Created mock server for development and testing environments',
        'Implemented comprehensive E2E testing (Cypress) and unit testing (Jest) for both Discovery Hub and Tucana',
        'Set up GitHub Actions CI for automated test runs',
        'Managed Docker containers for development and deployment',
      ],
      tech: 'Vue.js, Next.js, TypeScript, SCSS, WebSocket, Docker, Cypress, Jest, i18n, Monorepo',
    },
    {
      title: 'Product Manager & Technical Lead',
      company: 'YapoeY Bit',
      type: 'Studio',
      location: 'Seoul, Korea',
      duration: '2022/10 — Present',
      highlights: [
        'Founded and leading a development studio delivering full-stack web and mobile products',
        'Leading cross-functional teams across frontend, backend, and mobile development',
        'Delivered 10+ products for clients in Korea, Egypt, Qatar, and Japan',
        'Key projects:',
        '→ NooN Center (Egypt) — Full education platform with live/recorded courses, instructor portal, admin dashboard. Next.js 15, Express, MySQL. 576 commits',
        '→ Russian Whale (Egypt) — Compound & guest management with maintenance request system, 7 user roles. Nuxt 3, Express, MySQL. 547 commits',
        '→ bizNavi (Korea) — Enterprise mobile app with 33 feature modules (tasks, attendance, payments, patents). Flutter, BLoC. 816 commits',
        '→ ChaiTalk (Own) — Social networking app with real-time messaging. Flutter, Express, Socket.IO, DynamoDB, Redis. 193 commits',
        '→ Layun (Korea) — Product CMS with multilingual support (EN/ES/KO/RU). React, Express, PostgreSQL. 285 commits',
        '→ Seoul Bird (Korea) — Bird watching platform with KakaoMap integration. Nuxt 4, AWS S3. 55 commits',
        '→ Meya-Meya (Own) — AI-powered restaurant ordering with voice/text via Gemini AI. Nuxt 4 monorepo, NestJS. In development',
        '→ cTask (Korea) — Organization management web app. Vue.js 3, PrimeVue. 128 commits',
        '→ West East Forte (Korea) — B2B agency website. Nuxt 3, @nuxt/content. 27 commits',
      ],
      tech: 'Vue.js, Nuxt.js, Next.js, React, Flutter, Node.js, Express, NestJS, MySQL, PostgreSQL, DynamoDB, Redis, AWS, Docker',
    },
    {
      title: 'Frontend Developer',
      company: 'b2ggames',
      type: 'Full-time',
      location: 'Seoul, Korea',
      duration: '2021/12 — 2022/10',
      highlights: [
        'Built Asian Model Festival (AMF) event website from scratch',
        'Built Korean Baseball League fantasy gaming platform',
        'Daily maintenance of existing projects, debugging, and cross-browser compatibility',
        'Set documentation system using Notion',
        'Set onboarding program for new developers',
        'Implemented multiple languages (English, Korean)',
      ],
      tech: 'Nuxt.js, Vuex, SASS, Jira, Bitbucket',
    },
    {
      title: 'Frontend Developer',
      company: 'Himedi',
      type: 'Full-time',
      location: 'Seoul, Korea',
      duration: '2019/12 — 2021/11',
      highlights: [
        'Built medical tourism platform connecting Korean hospitals with international patients from scratch',
        'Implemented 3 languages (English, Arabic, Russian) with full RTL support',
        'Translated UI/UX wireframes to production code',
        'Enhanced application performance and scalability',
        'Ensured cross-browser compatibility',
      ],
      tech: 'Vue.js, Vuex, Bootstrap 4, Webpack, Axios, i18n, RTLCSS',
    },
    {
      title: 'Full Stack Developer',
      company: 'GeeksFamily',
      type: 'Full-time',
      location: 'Seoul, Korea',
      duration: '2019/02 — 2019/11',
      highlights: [
        'Built POS system and delivery sharing platform',
        'Developed food ordering web app',
        'Integrated Facebook, Google Analytics, and payment APIs',
        'Built daily order calculation reporting tool',
      ],
      tech: 'Vue.js, Laravel, MySQL, Chart.js, jQuery, Bootstrap',
    },
    {
      title: 'Full Stack Developer',
      company: 'Bio & Pure for Cosmetic',
      type: 'Freelance',
      location: 'Qatar',
      duration: '2016/05 — 2018/08',
      highlights: [
        'Designed and developed cosmetics e-commerce website from scratch',
        'Full frontend and backend implementation',
      ],
      tech: 'Laravel, Bootstrap 4, MySQL, JavaScript',
    },
  ]

  const education = [
    {
      degree: 'Computer Science & Engineering',
      school: 'Hanyang University',
      location: 'Seoul, Korea',
      year: '2015 — 2019',
    },
    {
      degree: 'Korean Language Program',
      school: 'Kyung Hee University',
      location: 'Seoul, Korea',
      year: '2014 — 2015',
    },
    {
      degree: 'Bachelor in Accounting',
      school: 'Ain Shams University',
      location: 'Cairo, Egypt',
      year: '2009 — 2013',
    },
  ]

  const skills = {
    frontend: ['Vue.js', 'Nuxt.js', 'React', 'Next.js', 'Flutter', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'SASS', 'Tailwind CSS', 'Bootstrap'],
    backend: ['Node.js', 'Express', 'NestJS', 'PHP', 'Laravel'],
    database: ['MySQL', 'PostgreSQL', 'DynamoDB', 'Redis'],
    cloud: ['AWS (S3, Lambda, EC2)', 'Docker', 'Google Cloud', 'Vercel'],
    tools: ['Git', 'GitHub', 'Bitbucket', 'Jira', 'ClickUp', 'Notion', 'Figma', 'Cypress', 'Jest', 'n8n', 'Claude AI'],
    languages: [
      { name: 'Arabic', level: 'Native', flag: '🇪🇬' },
      { name: 'English', level: 'Fluent', flag: '🇺🇸' },
      { name: 'Korean', level: 'Conversational', flag: '🇰🇷' },
    ],
  }

  const countries = [
    { name: 'South Korea', flag: '🇰🇷', note: 'Home since 2014' },
    { name: 'Egypt', flag: '🇪🇬', note: 'Home country' },
    { name: 'USA', flag: '🇺🇸', note: 'Sibel Health — FDA project' },
    { name: 'Japan', flag: '🇯🇵' },
    { name: 'China', flag: '🇨🇳' },
    { name: 'Taiwan', flag: '🇹🇼' },
    { name: 'Hong Kong', flag: '🇭🇰' },
    { name: 'Philippines', flag: '🇵🇭' },
    { name: 'Malaysia', flag: '🇲🇾' },
    { name: 'Vietnam', flag: '🇻🇳' },
    { name: 'Cambodia', flag: '🇰🇭' },
    { name: 'Laos', flag: '🇱🇦' },
    { name: 'Finland', flag: '🇫🇮' },
    { name: 'Estonia', flag: '🇪🇪' },
    { name: 'Poland', flag: '🇵🇱' },
    { name: 'Qatar', flag: '🇶🇦', note: 'Client project' },
    { name: 'Kuwait', flag: '🇰🇼' },
    { name: 'Saudi Arabia', flag: '🇸🇦' },
    { name: 'UAE', flag: '🇦🇪' },
    { name: 'Oman', flag: '🇴🇲' },
    { name: 'Jordan', flag: '🇯🇴' },
    { name: 'Yemen', flag: '🇾🇪' },
  ]

  const projects = [
    // Sibel Health
    {
      slug: 'sibel-central-monitoring',
      name: 'Central Monitoring System',
      description: 'Real-time patient monitoring platform tracking 64 patients simultaneously via WebSocket. Built the design system using atomic design methodology.',
      img: null,
      type: 'Frontend',
      tech: ['Vue.js', 'TypeScript', 'WebSocket', 'Docker', 'Cypress', 'Jest'],
      company: 'Sibel Health',
      role: 'Senior Frontend Developer & Team Lead',
      teamSize: null,
      url: null,
      highlights: [
        'Real-time monitoring of 64 patients via WebSocket',
        'Created Sibel Design System (atomic design) as shared npm package',
        'Optimized performance for live data streaming',
        'E2E testing with Cypress, unit testing with Jest',
        'Helped achieve FDA approval for Maternal project',
      ],
    },
    {
      slug: 'sibel-discovery-hub',
      name: 'Discovery Hub',
      description: 'Medical device management platform. Migrated entire codebase from React to Vue.js from scratch.',
      img: null,
      type: 'Frontend',
      tech: ['Vue.js', 'TypeScript', 'SCSS', 'Cypress', 'Jest', 'GitHub Actions'],
      company: 'Sibel Health',
      role: 'Senior Frontend Developer & Team Lead',
      teamSize: null,
      url: null,
      highlights: [
        'Migrated entire React codebase to Vue.js from scratch (256 commits)',
        'Built Itchy Sense product for Japanese company Maruho',
        'Created mock server for development/testing',
        'Set up GitHub Actions CI for automated tests',
      ],
    },
    // YapoeY Bit client projects
    {
      slug: 'noon-center',
      name: 'NooN Center',
      description: 'Full education platform with live/recorded courses, instructor portal, student dashboard, and admin panel.',
      img: null,
      type: 'Full Stack',
      tech: ['Next.js 15', 'React', 'Express', 'MySQL', 'AWS S3', 'JWT'],
      company: 'YapoeY Bit',
      role: 'Product Manager & Technical Lead',
      teamSize: 4,
      url: null,
      highlights: [
        'Live + recorded courses with flexible pricing',
        'Instructor portal with earnings management',
        'Admin dashboard with finance tracking',
        '576 commits across 3 repos (frontend, admin, backend)',
      ],
    },
    {
      slug: 'russian-whale',
      name: 'Russian Whale',
      description: 'Compound & guest management platform with maintenance request system and real-time chat.',
      img: null,
      type: 'Full Stack',
      tech: ['Nuxt 3', 'Vue 3', 'Express', 'MySQL', 'AWS S3', 'JWT'],
      company: 'YapoeY Bit',
      role: 'Product Manager & Technical Lead',
      teamSize: 5,
      url: null,
      highlights: [
        '7 user roles (Admin, Support Agent, Handyman, Guest, etc.)',
        'Real-time request tracking with messaging',
        'Guest portal with passport-based login',
        '547 commits across 3 repos',
      ],
    },
    {
      slug: 'biznavi',
      name: 'bizNavi',
      description: 'Enterprise mobile app with 33 feature modules for business operations management.',
      img: null,
      type: 'Full Stack',
      tech: ['Flutter', 'Dart', 'BLoC', 'Firebase', 'Shorebird'],
      company: 'YapoeY Bit',
      role: 'Product Manager & Technical Lead',
      teamSize: 3,
      url: null,
      highlights: [
        '33 feature modules (tasks, attendance, payments, patents)',
        'Hot-patch deployment via Shorebird',
        'Firebase push notifications',
        '816 commits — largest project',
      ],
    },
    {
      slug: 'chaitalk',
      name: 'ChaiTalk',
      description: 'Social networking & messaging app with real-time chat, timeline, posts, and media sharing.',
      img: null,
      type: 'Creative',
      tech: ['Flutter', 'Express', 'Socket.IO', 'DynamoDB', 'Redis', 'AWS S3'],
      company: 'Own Product',
      role: 'Founder & Lead Developer',
      teamSize: 5,
      url: null,
      highlights: [
        'Real-time messaging via Socket.IO',
        'Timeline with posts, polls, audio, GIFs',
        'Triple database: DynamoDB + MySQL + Redis',
        '193 commits (frontend + backend)',
      ],
    },
    {
      slug: 'layun',
      name: 'Layun',
      description: 'Product & content management platform with multilingual support in 4 languages.',
      img: null,
      type: 'Full Stack',
      tech: ['React 19', 'Vite', 'Express', 'PostgreSQL', 'AWS S3', 'Lexical'],
      company: 'YapoeY Bit',
      role: 'Product Manager & Technical Lead',
      teamSize: 3,
      url: null,
      highlights: [
        'Multilingual CMS (EN, ES, KO, RU)',
        'Rich text editor with image upload to S3',
        'CI/CD via GitHub Actions + Vercel',
        '285 commits across 2 repos',
      ],
    },
    {
      slug: 'seoul-bird',
      name: 'Seoul Bird',
      description: 'Bird watching community platform with interactive KakaoMap and species directory.',
      img: null,
      type: 'Full Stack',
      tech: ['Nuxt 4', 'Vue 3', 'KakaoMap API', 'Tailwind', 'AWS S3'],
      company: 'YapoeY Bit',
      role: 'Product Manager & Technical Lead',
      teamSize: 3,
      url: null,
      highlights: [
        'Interactive map with bird location markers',
        'Species directory with taxonomy management',
        'Admin dashboard with bulk Excel import/export',
        'Bilingual: Korean + English',
      ],
    },
    {
      slug: 'meya-meya',
      name: 'Meya-Meya',
      description: 'AI-powered restaurant ordering platform with voice and text ordering via Gemini AI.',
      img: null,
      type: 'Creative',
      tech: ['Nuxt 4', 'NestJS', 'TypeORM', 'MySQL', 'Gemini AI', 'FFmpeg'],
      company: 'Own Product',
      role: 'Founder & Lead Developer',
      teamSize: 2,
      url: null,
      highlights: [
        'AI chat ordering with voice (STT) and text',
        'Monorepo: customer app + provider dashboard + admin',
        'Custom SCSS design system with design tokens',
        'In active development',
      ],
    },
    {
      slug: 'ctask',
      name: 'cTask',
      description: 'Organization management web app with performance tracking and project management.',
      img: null,
      type: 'Frontend',
      tech: ['Vue.js 3', 'Vuex', 'PrimeVue', 'Tailwind', 'Google Maps'],
      company: 'YapoeY Bit',
      role: 'Product Manager & Technical Lead',
      teamSize: 2,
      url: null,
      highlights: [
        'Center introduction with org chart and history',
        'Business performance metrics dashboard',
        'Multi-language support with i18n',
        '128 commits',
      ],
    },
    {
      slug: 'west-east-forte',
      name: 'West East Forte',
      description: 'B2B digital agency website for cross-border market entry consulting.',
      img: null,
      type: 'Frontend',
      tech: ['Nuxt 3', 'Tailwind', '@nuxt/content', 'Nodemailer', 'i18n'],
      company: 'YapoeY Bit',
      role: 'Lead Developer',
      teamSize: 1,
      url: null,
      highlights: [
        'Bilingual (EN/KO) with SEO + Schema.org',
        'Contact form with Nodemailer',
        'Cloudflare integration',
      ],
    },
    // Previous work
    {
      slug: 'himedi',
      name: 'Himedi',
      description: 'Medical tourism platform connecting Korean hospitals with international patients.',
      img: 'himedi.png',
      type: 'Frontend',
      tech: ['Vue.js', 'Vuex', 'Bootstrap 4', 'Axios', 'i18n', 'RTLCSS'],
      company: 'Himedi',
      role: 'Frontend Developer',
      teamSize: null,
      url: 'https://himedi.com',
      highlights: [
        'Built frontend from scratch',
        '3 languages (EN, AR, RU) with full RTL support',
        'Cross-browser compatibility',
      ],
    },
    {
      slug: 'kbl',
      name: 'Korean Baseball League',
      description: 'Fantasy gaming platform for Korean baseball fans with real-time competition.',
      img: 'kbl.png',
      type: 'Frontend',
      tech: ['Nuxt.js', 'Vuex', 'SASS'],
      company: 'b2ggames',
      role: 'Frontend Developer',
      teamSize: null,
      url: 'https://kbl-pc.b2ggames.net',
      highlights: ['Fantasy gaming with real-time features', 'Multi-language (EN/KO)'],
    },
    {
      slug: 'amf',
      name: 'Asian Model Festival',
      description: 'Event website for AMF with voting and live competition features.',
      img: 'amf.png',
      type: 'Frontend',
      tech: ['Nuxt.js', 'Vuex'],
      company: 'b2ggames',
      role: 'Frontend Developer',
      teamSize: null,
      url: 'https://www.amffantasy.com/main',
      highlights: ['Built from scratch', 'Voting and live features'],
    },
    // 3D / Creative
    {
      slug: 'galaxy-3d',
      name: 'Galaxy 3D',
      description: 'Interactive 3D galaxy simulation with particle effects.',
      img: 'galaxy.png',
      type: 'Creative',
      tech: ['Three.js', 'WebGL'],
      company: 'Personal',
      role: 'Developer',
      teamSize: 1,
      url: 'https://s3.eu-west-3.amazonaws.com/yapoey.com/assets/sites/Galaxy/index.html',
      highlights: ['Interactive particle system', 'Browser-based 3D'],
    },
  ]

  const stats = {
    yearsExp,
    projects: '15+',
    countriesVisited: '22+',
    languages: 3,
    companies: 6,
    degrees: 2,
    commits: '6000+',
  }

  return { bio, experience, education, skills, projects, countries, stats }
}
